/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module halfAdder (
  input A,
  input B,
  output S,
  output C
);
  assign S = (A ^ B);
  assign C = (A & B);
endmodule

module fullAdder (
  input A,
  input B,
  input Ci,
  output Co,
  output S
);
  wire s0;
  wire s1;
  wire s2;
  halfAdder halfAdder_i0 (
    .A( A ),
    .B( B ),
    .S( s0 ),
    .C( s2 )
  );
  halfAdder halfAdder_i1 (
    .A( Ci ),
    .B( s0 ),
    .S( S ),
    .C( s1 )
  );
  assign Co = (s1 | s2);
endmodule

module \4bitRCAdder  (
  input B0,
  input A0,
  input Ci,
  input A1,
  input B1,
  input B2,
  input A2,
  input B3,
  input A3,
  output S0,
  output S1,
  output S2,
  output S3,
  output Co
);
  wire s4;
  wire s5;
  wire s6;
  fullAdder fullAdder_i0 (
    .A( A0 ),
    .B( B0 ),
    .Ci( Ci ),
    .Co( s4 ),
    .S( S0 )
  );
  fullAdder fullAdder_i1 (
    .A( A1 ),
    .B( B1 ),
    .Ci( s4 ),
    .Co( s5 ),
    .S( S1 )
  );
  fullAdder fullAdder_i2 (
    .A( A2 ),
    .B( B2 ),
    .Ci( s5 ),
    .Co( s6 ),
    .S( S2 )
  );
  fullAdder fullAdder_i3 (
    .A( A3 ),
    .B( B3 ),
    .Ci( s6 ),
    .Co( Co ),
    .S( S3 )
  );
endmodule
